// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ProtoType.proto

package protocol

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//协议号
type MSGTYPE int32

const (
	MSGTYPE_Mt_C2S_TestMessage MSGTYPE = 0
	MSGTYPE_Mt_S2C_TestMessage MSGTYPE = 10000
)

var MSGTYPE_name = map[int32]string{
	0:     "Mt_C2S_TestMessage",
	10000: "Mt_S2C_TestMessage",
}

var MSGTYPE_value = map[string]int32{
	"Mt_C2S_TestMessage": 0,
	"Mt_S2C_TestMessage": 10000,
}

func (x MSGTYPE) String() string {
	return proto.EnumName(MSGTYPE_name, int32(x))
}

func (MSGTYPE) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_3f0a87896b3b6436, []int{0}
}

func init() {
	proto.RegisterEnum("protocol.MSGTYPE", MSGTYPE_name, MSGTYPE_value)
}

func init() { proto.RegisterFile("ProtoType.proto", fileDescriptor_3f0a87896b3b6436) }

var fileDescriptor_3f0a87896b3b6436 = []byte{
	// 97 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x0f, 0x28, 0xca, 0x2f,
	0xc9, 0x0f, 0xa9, 0x2c, 0x48, 0xd5, 0x2b, 0x00, 0xb1, 0x84, 0x38, 0xc0, 0x54, 0x72, 0x7e, 0x8e,
	0x96, 0x15, 0x17, 0xbb, 0x6f, 0xb0, 0x7b, 0x48, 0x64, 0x80, 0xab, 0x90, 0x18, 0x97, 0x90, 0x6f,
	0x49, 0xbc, 0xb3, 0x51, 0x70, 0x7c, 0x48, 0x6a, 0x71, 0x89, 0x6f, 0x6a, 0x71, 0x71, 0x62, 0x7a,
	0xaa, 0x00, 0x83, 0x90, 0x38, 0x58, 0x3c, 0xd8, 0xc8, 0x19, 0x45, 0x7c, 0x82, 0x5f, 0x12, 0x1b,
	0xd8, 0x14, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x5f, 0x6a, 0x28, 0x77, 0x5f, 0x00, 0x00,
	0x00,
}
