// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProtoType.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using scg = global::System.Collections.Generic;
namespace Protocol {

  #region Enums
  /// <summary>
  ///协议号
  /// </summary>
  public enum MSGTYPE {
    /// <summary>
    ///C2S测试
    /// </summary>
    MtC2STestMessage = 0,
    /// <summary>
    ///加入
    /// </summary>
    MtC2SJoin = 1,
    /// <summary>
    ///S2C测试
    /// </summary>
    MtS2CTestMessage = 10000,
    /// <summary>
    ///地图初始化
    /// </summary>
    MtS2CMapInit = 10001,
    /// <summary>
    ///地图更新
    /// </summary>
    MtS2CMapRand = 10002,
  }

  #endregion

}

#endregion Designer generated code
