// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProtoType.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using scg = global::System.Collections.Generic;
namespace Protocol {

  #region Enums
  /// <summary>
  ///协议号
  /// </summary>
  public enum MSGTYPE {
    /// <summary>
    ///登录
    /// </summary>
    C2StestMessage = 0,
    /// <summary>
    ///登录返回
    /// </summary>
    S2CtestMessage = 10000,
  }

  #endregion

}

#endregion Designer generated code
